### PR TITLE
Fixed gradle deprecated features

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I have run `./gradlew installLocal`

#### Why is this the best possible solution? Were any other approaches considered?
I've just fixed deprecated features. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
`installLocall` still fails for me if I don't remove `maven-javadoc-plugin` with:
> MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.

but it seem like there is everything fine with `JAVA_HOME`... does anyone else experience the same?

**Comment by seadowg** [comment]
> but it seem like there is everything fine with JAVA_HOME... does anyone else experience the same?

Is this on Linux? Are you able to just run `javadoc` (or `which javadoc`) from the javarosa project dir? Also, what does `echo $JAVA_HOME` output?

**Comment by grzesiek2010** [comment]
> Is this on Linux?

Yes.

`./gradlew javadoc` works fine for example. It used to fail for the same reason `JAVA_HOME is not correctly set` because it wasn't set indeed but I've fixed it and it works well. But `./gradlew installLocall` does not. 
`echo $JAVA_HOME ` says `/usr/lib/jvm/java-17-openjdk-amd64` I've tried some other configurations and to no avail. If it works for `./gradlew javadoc` it should also work for `./gradlew installLocall` I think.

**Comment by seadowg** [comment]
> ./gradlew javadoc works fine for example.

I just mean literally `javadoc` on it's own. It looks like maven is having a hard time finding the Java Doc binary. `installLocal` uses a maven build, not a Gradle one so it might be that the maven build process is not working on your machine.

**Comment by grzesiek2010** [comment]
> I just mean literally javadoc on it's own. It looks like maven is having a hard time finding the Java Doc binary. installLocal uses a maven build, not a Gradle one so it might be that the maven build process is not working on your machine.

Yeah, there is something wrong there but I've upgraded the plugin https://github.com/getodk/javarosa/pull/732/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R129 and it fixes the issue so I think it's ok and I don't have to think about it more at least for now.

**Review by seadowg — APPROVED** [review]

**Pull request merged**
