### PR TITLE
616 CSV parsing improvements-WIP

### LINKED ISSUE #616: Support quotes, escaped commas, and other CSV formatting in external CSV files
#### Software versions 
All

#### Problem description
CSVs are split on commas with no accounting for standard CSV formatting.

#### Steps to reproduce the problem
[select-one-file.zip](https://github.com/getodk/javarosa/files/5700809/select-one-file.zip)

#### Expected behavior
Standard CSV formatting is handled.

### PR DESCRIPTION
**Pull request by dcbriccetti**
Closes #616

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for thinking to use the lib. That is much better than rolling our own.

Unfortunately I don't remember much about how the Android API level checker works! It looks more like a mechanical issue getting the lib recognized than an actual failure which is good.

**Comment by lognaturel** [comment]
@dcbriccetti This is starting to feel more pressing. Would you have a chance to finish soon or do you prefer to hand off?

**Comment by dcbriccetti** [comment]
> @dcbriccetti This is starting to feel more pressing. Would you have a chance to finish soon or do you prefer to hand off?

Apologies for the delay. Resuming now.

**Comment by lognaturel** [comment]
Thank you! I did recently update the Android API checker. If it still fails after a rebase on master, I can look into it.

**Comment by dcbriccetti** [comment]
Hmm, the failing tests all call `configureReferenceManagerIncorrectly`, for what that’s worth. So far I don’t see that the failures are related to this change.

**Comment by lognaturel** [comment]
Thanks for doing most of the legwork here.

The test failures are because there was a `FileNotFoundException` expected that is now a `FileSystemException`. It's related to the change at https://github.com/getodk/javarosa/commit/847865c78512af9b65211ea332d23e17c119fa07. I'll close this and reopen a PR off my branch.

**Comment by lognaturel** [comment]
Unfortunately, this would require API 26. We have a min API level of 21. Maybe we can use an older version of `commons-csv`, I'm not sure.

**Comment by lognaturel** [comment]
v1.4 works. New PR at #644.

**Pull request closed without merging**
